-- CreateTable
CREATE TABLE "OrganizationSettings" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "vatRegistered" BOOLEAN NOT NULL DEFAULT false,
    "vatEffectiveDate" TIMESTAMP(3),
    "reverseChargeEnabled" BOOLEAN NOT NULL DEFAULT false,
    "simplifiedInvoiceThreshold" DECIMAL(15,2) NOT NULL DEFAULT 10000,
    "showLogo" BOOLEAN NOT NULL DEFAULT true,
    "showQrCode" BOOLEAN NOT NULL DEFAULT true,
    "showBankDetails" BOOLEAN NOT NULL DEFAULT false,
    "showSignature" BOOLEAN NOT NULL DEFAULT false,
    "showStamp" BOOLEAN NOT NULL DEFAULT false,
    "showWatermark" BOOLEAN NOT NULL DEFAULT false,
    "watermarkText" TEXT,
    "invoiceFooter" TEXT,
    "bankName" TEXT,
    "bankAccountName" TEXT,
    "bankAccountNumber" TEXT,
    "bankIban" TEXT,
    "bankSwift" TEXT,
    "bankBranch" TEXT,
    "stripePublishableKey" TEXT,
    "stripeSecretKeyHash" TEXT,
    "stripeWebhookSecret" TEXT,
    "paybyMerchantId" TEXT,
    "paybySecretKeyHash" TEXT,
    "emailFromName" TEXT,
    "emailFromAddress" TEXT,
    "sendInvoiceCopy" BOOLEAN NOT NULL DEFAULT false,
    "autoReminders" BOOLEAN NOT NULL DEFAULT true,
    "reminderDaysBefore" INTEGER[] DEFAULT ARRAY[3, 7]::INTEGER[],
    "reminderDaysAfter" INTEGER[] DEFAULT ARRAY[3, 7, 14]::INTEGER[],
    "lateFeeEnabled" BOOLEAN NOT NULL DEFAULT false,
    "lateFeeType" TEXT NOT NULL DEFAULT 'PERCENTAGE',
    "lateFeeValue" DECIMAL(8,2),
    "lateFeeDays" INTEGER,
    "timezone" TEXT NOT NULL DEFAULT 'Asia/Dubai',
    "dateFormat" TEXT NOT NULL DEFAULT 'DD/MM/YYYY',
    "numberFormat" TEXT NOT NULL DEFAULT 'en-AE',
    "language" TEXT NOT NULL DEFAULT 'en',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OrganizationSettings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "OrganizationSettings_organizationId_key" ON "OrganizationSettings"("organizationId");
